url: https://github.com/kubernetes/ingress-nginx/releases/download/ingress-nginx-3.3.0/ingress-nginx-3.3.0.tgz
packageVersion: 02
# This repository does not use releaseCandidateVersions, so you can leave this as 00.
releaseCandidateVersion: 00
